//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaia.WebWidgets.Samples.Extensions.Window.Nested {
    
    
    /// <summary>
    /// Default class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Default {
        
        /// <summary>
        /// zNumberOfWindows control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.DropDownList zNumberOfWindows;
        
        /// <summary>
        /// zModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.CheckBox zModal;
        
        /// <summary>
        /// zOpenFirstWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Button zOpenFirstWindow;
    }
}
