//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaia.WebWidgets.Samples.Core.DynamicControls.Overview {
    
    
    public partial class Default {
        
        /// <summary>
        /// zCreateTimer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Button zCreateTimer;
        
        /// <summary>
        /// zMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Label zMessage;
        
        /// <summary>
        /// zContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Panel zContainer;
    }
}
