//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaia.WebWidgets.Samples.Effects.EffectContainers.EffectQueue {
    
    
    public partial class Default {
        
        /// <summary>
        /// GDoc1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Samples.UI.GDoc GDoc1;
        
        /// <summary>
        /// zButtonFire control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Button zButtonFire;
        
        /// <summary>
        /// zWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Extensions.Window zWindow;
        
        /// <summary>
        /// zFireEffect control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.LinkButton zFireEffect;
    }
}
