//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaia.WebWidgets.Samples.Aspects.AspectDraggable.Ghosting {
    
    
    public partial class Default {
        
        /// <summary>
        /// zGhostLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Label zGhostLabel1;
        
        /// <summary>
        /// zGhostImage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Image zGhostImage1;
        
        /// <summary>
        /// zGhostLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Label zGhostLabel2;
        
        /// <summary>
        /// zGhostPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Panel zGhostPanel;
        
        /// <summary>
        /// zGhostImage2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Image zGhostImage2;
        
        /// <summary>
        /// zGhostLabel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Label zGhostLabel3;
        
        /// <summary>
        /// zGhostImage3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Image zGhostImage3;
    }
}
