//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaia.WebWidgets.Samples.Aspects.AspectUpdateControl.Overview {
    
    
    public partial class Default {
        
        /// <summary>
        /// GDoc1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Samples.UI.GDoc GDoc1;
        
        /// <summary>
        /// zButtonNotLengthy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Button zButtonNotLengthy;
        
        /// <summary>
        /// zButtonLengthy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Button zButtonLengthy;
        
        /// <summary>
        /// zUpdateControlButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Panel zUpdateControlButton;
        
        /// <summary>
        /// zCheckBoxNotLengthy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.CheckBox zCheckBoxNotLengthy;
        
        /// <summary>
        /// zCheckBoxLengthy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.CheckBox zCheckBoxLengthy;
        
        /// <summary>
        /// zUpdateControlCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Panel zUpdateControlCheckBox;
        
        /// <summary>
        /// zLinkButtonNotLengthy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.LinkButton zLinkButtonNotLengthy;
        
        /// <summary>
        /// zLinkButtonLengthy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.LinkButton zLinkButtonLengthy;
        
        /// <summary>
        /// zUpdateControlLinkButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.Panel zUpdateControlLinkButton;
        
        /// <summary>
        /// zDelay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gaia.WebWidgets.DropDownList zDelay;
    }
}
